# Generated by Django 4.2 on 2024-05-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samurai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samurai',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='samurai',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='samurai',
            index=models.Index(fields=['-time_create'], name='samurai_sam_time_cr_255dd5_idx'),
        ),
    ]
