# Generated by Django 4.2 on 2024-05-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samurai', '0002_alter_samurai_options_samurai_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samurai',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
        migrations.AlterField(
            model_name='samurai',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
