# Generated by Django 4.2 on 2024-05-17 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samurai', '0004_category_samurai_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samurai',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samurai.category'),
        ),
    ]
