# Generated by Django 4.2 on 2024-06-07 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samurai', '0006_posttag_alter_samurai_category_samurai_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lifework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='samurai',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='samurais', to='samurai.posttag'),
        ),
        migrations.AddField(
            model_name='samurai',
            name='lifework',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='samurai.lifework'),
        ),
    ]
