# Generated by Django 4.2 on 2024-06-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samurai', '0007_lifework_alter_samurai_tags_samurai_lifework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samurai',
            name='lifework',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='samurai.lifework'),
        ),
    ]
